#ifndef const_h
#define const_h

#define NUM_PES 16

#define DEFAULT_STREAM_DEPTH 16

#define A_IN_WIDTH 64
#define A_MEMORY_SPACE_ADDR_WIDTH 32
#define A_META_IN_WIDTH 32
#define A_META_MEMORY_SPACE_ADDR_WIDTH 32
#define B_IN_WIDTH 64
#define B_MEMORY_SPACE_ADDR_WIDTH 32
#define B_META_IN_WIDTH 32
#define B_META_MEMORY_SPACE_ADDR_WIDTH 32
#define OUT_WIDTH 32
#define OUT_MEMORY_SPACE_ADDR_WIDTH 32

#define A_DENSE_OBJECT_DATA_WIDTH (A_MEMORY_SPACE_ADDR_WIDTH + 128)
#define B_DENSE_OBJECT_DATA_WIDTH (B_MEMORY_SPACE_ADDR_WIDTH + 128)

#define MAX_A_ROWS 1024
#define MAX_B_COLS 1024

#endif 